version: "3.8"
services:
  service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin
    ports:
      - "9200:9200"
      - "9300:9300"
